#域名配置
#domainname: http://60.175.245.67
server:
#  address: 192.168.1.102
  port: 8821
  servlet:
    context-path: /APP
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.80.133:3306/zhongjian_bao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
  #  url: jdbc:mysql://localhost:3306/purchase?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: a123456
   # username: root
   # password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1
  redis:
    database: 0
    host: 47.99.80.133
    #host: 127.0.0.1
    port: 6379
    password: zjb_zzl#
    timeout: 100000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-request-size: 5000MB
      max-file-size: 5000MB
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /**
      suffix: /**
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static

# mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
  mapper-locations: mybatis/*Mapper.xml
  typeAliasesPackage: com.zhongjianbaoapi.entity
logging:
  level:
    root: info
    com.procurementapi.dao: debug
#是否激活 swagger true or false
swagger:
  enable: true
#文件上传配置
upload:
  uploadPath: E://uploadFiles/APP/
  #uploadPath: /www/wwwroot/juzicaigou/uploadFiles/APP/
  filePath: /files/
#ftp配置
custom:
  file-server:
    ip: 47.99.80.133
    port: 21
  file-ftp-user:
  file-ftp-password:
  file-savepath: /files/



